version: v{build}
image: Visual Studio 2015
environment:
  Qt5_DIR: 'C:\Qt\5.11.0\msvc2015'
  PATH: '%Qt5_DIR%\bin;%PATH%'
install:
- git submodule update --init --recursive
- git clone https://github.com/mlomb/OrbitEngine.git ../OrbitEngine --recursive
before_build:
- ps: . "Tools/Build/Windows/build.ps1"
build:
  project: Build/Windows/OrbitEngineEditor.sln
  verbosity: minimal
artifacts:
- path: Build\Windows\Release\Editor.exe
  name: Editor.exe